// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/caozhangni/k8s-controller-custom-resource/pkg/apis/samplecrd/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// NetworkLister helps list Networks.
// All objects returned here must be treated as read-only.
type NetworkLister interface {
	// List lists all Networks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.Network, err error)
	// Networks returns an object that can list and get Networks.
	Networks(namespace string) NetworkNamespaceLister
	NetworkListerExpansion
}

// networkLister implements the NetworkLister interface.
type networkLister struct {
	listers.ResourceIndexer[*v1.Network]
}

// NewNetworkLister returns a new NetworkLister.
func NewNetworkLister(indexer cache.Indexer) NetworkLister {
	return &networkLister{listers.New[*v1.Network](indexer, v1.Resource("network"))}
}

// Networks returns an object that can list and get Networks.
func (s *networkLister) Networks(namespace string) NetworkNamespaceLister {
	return networkNamespaceLister{listers.NewNamespaced[*v1.Network](s.ResourceIndexer, namespace)}
}

// NetworkNamespaceLister helps list and get Networks.
// All objects returned here must be treated as read-only.
type NetworkNamespaceLister interface {
	// List lists all Networks in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.Network, err error)
	// Get retrieves the Network from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.Network, error)
	NetworkNamespaceListerExpansion
}

// networkNamespaceLister implements the NetworkNamespaceLister
// interface.
type networkNamespaceLister struct {
	listers.ResourceIndexer[*v1.Network]
}
